### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by hastebrot** [wprl/baucis#269] opened 2015-05-29 17:21 UTC
JSON API 1.0 was finalized today.

- http://jsonapi.org/
- https://github.com/json-api/json-api/pull/727

> A specification for building JSON API.
>If you've ever argued with your team about the way your JSON responses should be formatted, JSON API is your anti-bikeshedding weapon.

My question is: Does Baucis follow JSON API formatting rules or is it feasible to adapt these rules?

**Comment by wprl** [comment] 2015-05-29 17:48
Thanks for your inquiry.  This is a duplicate of #98.  Currently the plan is to go forward with HAL in the near future but that doesn't preclude adding support for JSON API.

**Closed by wprl** 2015-05-29 17:48 UTC
