### ISSUE TITLE
Support mongoose-deep-populate

### ISSUE THREAD

**Issue by Tchouk** [wprl/baucis#240] opened 2015-03-06 20:35 UTC
I use [mongoose-deep-populate](https://github.com/buunguyen/mongoose-deep-populate) plugin (v1.0.0) which allows me to use deepPopulate() instead the classic mongoose populate() to populate nested models at any level of depth.

Imagine following schemas :
```javascript
var UserSchema = new Schema({})

var CommentSchema = new Schema({
  user  : {type: Number, ref: 'User'}
})

var PostSchema = new Schema({
  user    : {type: Number, ref: 'User'},
  comments: [{type: Number, ref: 'Comment'}],
  likes   : [{user: {type: Number, ref: 'User'}}],
  approved: {status: Boolean, user: {type: Number, ref: 'User'}} 
})

var deepPopulate = require('mongoose-deep-populate');
PostSchema.plugin(deepPopulate, options);
```

The deep population works with the following code : 
```javascript
Post.findOne({}).deepPopulate('comments.user').exec(function (err, post) { ... });
```
But it would be so much better to do that in a baucis middleware: 
```javascript
var controller = baucis.rest(Post);
controller.query(function (request, response, next) {
  request.baucis.query.deepPopulate('comments.user');
  next();
});
```
Should we not be able to use deepPopulate () as in the above example (like we can use populate()) ?

**Comment by wprl** [comment] 2015-03-06 20:58
Yes, you should be able to do that.  I was speaking with someone else via email about this that I believe was having an issue wit this because a bug in the baucis package.json caused multiple versions of mongoose to be installed to the dependency tree.  The issue should be resolved in 1.0.0, but please reopen if you run into any trouble!

**Comment by Tchouk** [comment] 2015-03-07 13:34
I tested with baucis v1.0.3 and I have the same trouble despite the use of a single version of mongoose (v3.8.23).

**Comment by wprl** [comment] 2015-03-07 15:19
Can you try deleting the node_modules entirely and running npm install again?

**Comment by Tchouk** [comment] 2015-03-07 17:44
This is what I done and the trouble persists.

**Comment by wprl** [comment] 2015-03-09 15:37
Looks like mongoose-deep-populate doesn't work with Mongoose's query.stream.  You might open an issue over there https://github.com/buunguyen/mongoose-deep-populate/issues

I've added a (failing) regression test for this so if they address the issue with streams there will be a test already in place if you have any more trouble.

Sorry I can't be of more help.

**Closed by wprl** 2015-03-09 15:37 UTC
Labels: verify with regression test

**Comment by fgnass** [comment] 2015-10-30 20:14
I just ran into the same (?) problem using a plain Mongoose middleware instead of the deep-populate plugin:

```js
schema.pre('findOne', function(next) {
  this.populate('lastModifiedBy', 'email');
  next();
});

schema.pre('find', function(next) {
  this.populate('lastModifiedBy', 'email');
  next();
});
```

When I `GET` a resource, neither of these functions gets called and the Mongoose log just says:

```js
Mongoose: persons.find({ _id: 1 }) { fields: undefined }
```

Whereas manually calling `Person.findOne({ _id: 1 })` results in:
```js
Mongoose: persons.findOne({ _id: 1 }) { fields: undefined }
Mongoose: persons.find({ _id: { '$in': [ 2 ] } }) { fields: { email: 1 } }
Mongoose: persons.find({ _id: { '$in': [ 2 ] } }) { fields: { email: 1 } }
```

You mentioned that baucis uses Query#stream() – can you point me to the code? I didn't find the place where the query gets executed. Could it be that Mongoose doesn't invoke its middleware in streaming mode?

**Comment by timbur** [comment] 2015-10-30 22:31
`mongoose` has deep population as of version 4.1.  See https://github.com/Automattic/mongoose/pull/3103 and prl/baucis/commit/91431695e4be8cfa0879c2dbb17185cb3e5b2036 and https://github.com/loggur/baucis-decorator-deep-select.
